### ISSUE TITLE
stage1/network-loader: stage2.bin is fetched but not written to disk

### ISSUE THREAD

**Issue by tuxuser** [exploits-forsale/solstice#4]
~~^ will send a fix in a bit~~

Nevermind, it looks intentional as it is, as the daemon-supporting collateral damage post_exploit payload is a wip.

**Comment by landaire** [comment]
Yeah, this was intentional _mostly_ to prevent adding unnecessary code to the gamescript exploit which would cause its size to inflate. While `run.exe` is only written to disk since stage2 depends on it being on-disk.

I'm not opposed to writing it so long as the the GS exploit doesn't fail. Probably nobody except emma and I have encountered this yet, but if the shellcode array hits too many elements GS starts bugging out with random script errors.
